title: wez.svr
description: jsライブラリなどのデータベース
url: https://wezset.github.io/wez.svr/
author: wezset
google_analytics: UA-218058024-1

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-seo-tag

# multilang
languages: ['ja', 'ko', 'en']
default_lang: 'ja'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false
